import { StyleSheet } from "react-native";

export const colors = {
  backgroundHomeLinearFrom: "#004689",
  backgroundHomeLinearTo: "#002863",
  backgroundOtherLinearFrom: "#3F3F47",
  backgroundOtherLinearTo: "#070709",
  card: {
    backgroundColor: "#151A31",
    borderColor: "#363A4E",
  },
  textTitle: "#FFFFFF",
  textSubtitle: "#B4C0FF",
  text: "#FFFFFF",
  glassTab: {
    mainPillBorderOuter: "rgba(255,255,255,0.14)",
    mainPillBorderInner: "rgba(255,255,255,0.08)",
    mainPillBackground: "rgba(10,12,16,0.72)",
    shadow: "rgba(0,0,0,0.44)",
    shine: "transparent",
    activeBackground: "rgba(255,255,255,0.12)",
    activeBorder: "rgba(255,255,255,0.24)",
    activeShadow: "rgba(0,0,0,0.26)",
    label: "rgba(255,255,255,0.78)",
    labelActive: "#ff496a",
    iconActive: "#ff496a",
    iconInactive: "rgba(255,255,255,0.80)",
    sideIcon: "rgba(255,255,255,0.90)",
    sideOrbBackground: "rgba(10,12,16,0.72)",
    sideOrbBorderOuter: "rgba(255,255,255,0.14)",
    sideOrbBorderInner: "rgba(255,255,255,0.08)",
    sideOrbGlow: "transparent",
    blurMainIntensity: 62,
    blurSideIntensity: 62,
    blurTint: "dark",
  },
};

export const text = StyleSheet.create({
  title: {
    fontFamily: "SFProDisplay-Bold",
    fontSize: 24,
    fontWeight: "700",
  },
  subtitle: {
    fontFamily: "SFProDisplay-Regular",
    fontSize: 18,
    fontWeight: "400",
  },
  text: {
    fontFamily: "SFProDisplay-Regular",
    fontSize: 12,
    fontWeight: "400",
  },
});

export const elements = StyleSheet.create({
  card: {
    backgroundColor: colors.card.backgroundColor,
    borderColor: colors.card.borderColor,
    borderRadius: 10,
  },
  title: {
    color: colors.textTitle,
    ...text.title,
  },
  subtitle: {
    color: colors.textSubtitle,
    ...text.subtitle,
  },
  text: {
    color: colors.text,
    ...text.text,
  },
  glassTabMainPill: {
    flex: 1,
    position: "relative",
    flexDirection: "row",
    borderRadius: 32,
    borderWidth: 0.8,
    overflow: "hidden",
    padding: 5,
    borderColor: colors.glassTab.mainPillBorderOuter,
    backgroundColor: colors.glassTab.mainPillBackground,
    shadowColor: colors.glassTab.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 8,
  },
  glassTabBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  glassTabInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 32,
    borderWidth: 0.6,
    borderColor: colors.glassTab.mainPillBorderInner,
  },
  glassTabShine: {
    position: "absolute",
    top: 2,
    left: 14,
    right: 14,
    height: "40%",
    backgroundColor: colors.glassTab.shine,
    borderBottomLeftRadius: 56,
    borderBottomRightRadius: 56,
  },
  glassTabItem: {
    flex: 1,
    borderRadius: 26,
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  glassTabActive: {
    borderWidth: 0.8,
    backgroundColor: colors.glassTab.activeBackground,
    borderColor: colors.glassTab.activeBorder,
    shadowColor: colors.glassTab.activeShadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 9,
    elevation: 4,
  },
  glassTabLabel: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.glassTab.label,
  },
  glassTabLabelActive: {
    fontWeight: "600",
    color: colors.glassTab.labelActive,
  },
  glassTabSideAction: {
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 0.8,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderColor: colors.glassTab.sideOrbBorderOuter,
    backgroundColor: colors.glassTab.sideOrbBackground,
    shadowColor: colors.glassTab.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 8,
  },
  glassTabSideActionBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  glassTabSideActionInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 31,
    borderWidth: 0.6,
    borderColor: colors.glassTab.sideOrbBorderInner,
  },
  glassTabSideActionGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 26,
    backgroundColor: "transparent",
    shadowColor: colors.glassTab.sideOrbGlow,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  glassTabSideActionShine: {
    position: "absolute",
    top: 2,
    left: 8,
    right: 8,
    height: "40%",
    backgroundColor: colors.glassTab.shine,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  glassTabIconActive: {
    color: colors.glassTab.iconActive,
  },
  glassTabIconInactive: {
    color: colors.glassTab.iconInactive,
  },
  glassTabWrapper: {
    left: 14,
    right: 14,
    position: "absolute",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
});
